version: '3.7'
services:
  frontend:
    container_name: frontend
    build: .
    volumes:
      - './:/app'
      - '/app/node_modules'
    ports:
      - 80:80
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file:
      - .env